---
name: assignments
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.0 <3.0.0'
dependencies:
  animated_splash_screen: ^1.3.0
  cloud_firestore: ^4.8.4
  cupertino_icons: ^1.0.2
  firebase_auth: ^4.7.2
  firebase_core: ^2.14.0
  firebase_storage: ^11.2.4
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.1
  flutter_plugin_android_lifecycle: ^2.0.16
  geocode: ^1.0.3
  geocoding: ^2.1.0
  geolocator: ^10.1.0
  get: ^4.6.5
  google_fonts: ^5.1.0
  google_nav_bar: ^5.0.6
  hive: ^2.2.3
  image_picker: ^0.8.4+2
  intl: ^0.18.1
  line_awesome_flutter: ^2.0.0
  path: ^1.8.3
  path_provider: ^2.1.1
  provider: ^6.0.5
  snippet_coder_utils: ^1.0.14
  sqflite: ^2.3.0
  sticky_headers: ^0.3.0+2
dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/
