// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOIeVbzax12tlVwjKbIKeEx568bifaJlc',
    appId: '1:974992529454:web:e11b292cf80dd43ff1a7bf',
    messagingSenderId: '974992529454',
    projectId: 'please-2d282',
    authDomain: 'please-2d282.firebaseapp.com',
    storageBucket: 'please-2d282.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUWicVl_4_iehDT_8QchCxQebJD745vBk',
    appId: '1:974992529454:android:0a3db711c5186c47f1a7bf',
    messagingSenderId: '974992529454',
    projectId: 'please-2d282',
    storageBucket: 'please-2d282.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrK65fuZzXWNgoOSXc1jIiwG18PSxzt7w',
    appId: '1:974992529454:ios:fcb226266679eff2f1a7bf',
    messagingSenderId: '974992529454',
    projectId: 'please-2d282',
    storageBucket: 'please-2d282.appspot.com',
    iosClientId: '974992529454-cjfqtqboo351j4bmfdcad2a6rbb8fr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrK65fuZzXWNgoOSXc1jIiwG18PSxzt7w',
    appId: '1:974992529454:ios:2ebb3e14a83099d2f1a7bf',
    messagingSenderId: '974992529454',
    projectId: 'please-2d282',
    storageBucket: 'please-2d282.appspot.com',
    iosClientId: '974992529454-a2gn8k4pk5o5noqk3org9lvhja2s0lh3.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled.RunnerTests',
  );
}
